# Generated by Django 3.0.3 on 2020-10-03 19:02

from django.db import migrations, models
import django.db.models.deletion
import django_extensions.db.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Chronology',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('name', models.CharField(max_length=250, verbose_name='Cronologia')),
            ],
            options={
                'verbose_name': 'Cronologia',
                'verbose_name_plural': 'Cronologias',
            },
        ),
        migrations.CreateModel(
            name='FunerarySite',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('name', models.CharField(max_length=250, verbose_name='Nome do Sítio')),
                ('burial_type', models.TextField(verbose_name='Tipo/número de enterramentos')),
                ('burial', models.CharField(choices=[('P', 'Primário'), ('S', 'Secundário'), ('PS', 'Primário e Secundário'), ('MS', 'Não Mencionado')], default='P', max_length=2, verbose_name='Tipo de Inumação')),
                ('uf', models.CharField(choices=[('AC', 'Acre'), ('AL', 'Alagoas'), ('AP', 'Amapa'), ('AM', 'Amazonas'), ('BA', 'Bahia'), ('CE', 'Ceará'), ('ES', 'Espirito Santo'), ('GO', 'Goiás'), ('MA', 'Maranhão'), ('MT', 'Mato Grosso'), ('MS', 'Mato Grosso do Sul'), ('MG', 'Minas Gerais'), ('PA', 'Pará'), ('PB', 'Paraíba'), ('PR', 'Paraná'), ('PE', 'Pernambuco'), ('PI', 'Piauí'), ('RJ', 'Rio de Janeiro'), ('RN', 'Rio Grande do Norte'), ('RS', 'Rio Grande do Sul'), ('RO', 'Rondônia'), ('RR', 'Roraima'), ('SC', 'Santa Catarina'), ('SP', 'São Paulo'), ('SE', 'Sergipe'), ('TO', 'Tocantins'), ('DF', 'Distrito Federal')], default='AC', max_length=2, verbose_name='Distrito')),
                ('county', models.CharField(max_length=250, verbose_name='Município')),
                ('dating', models.TextField(verbose_name='Datação')),
                ('dated_material', models.TextField(verbose_name='Material Datado')),
                ('chronology', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='funeral.Chronology')),
            ],
            options={
                'verbose_name': 'Sítio Funerário',
                'verbose_name_plural': 'Sítios Funerários',
            },
        ),
        migrations.CreateModel(
            name='Reference',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('name', models.CharField(max_length=250)),
            ],
            options={
                'verbose_name': 'Referência',
                'verbose_name_plural': 'Referências',
            },
        ),
        migrations.CreateModel(
            name='SiteType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('initials', models.CharField(max_length=20, verbose_name='Tipo do Sítio')),
                ('description', models.CharField(max_length=250, verbose_name='Descrição')),
            ],
            options={
                'verbose_name': 'Tipo de Sítio',
                'verbose_name_plural': 'Tipos de Sítios',
            },
        ),
        migrations.CreateModel(
            name='SiteImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('title', models.CharField(max_length=250, verbose_name='Título')),
                ('description', models.TextField(verbose_name='Descrição')),
                ('src', models.ImageField(upload_to='images/')),
                ('funeral_site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='funeral.FunerarySite')),
            ],
            options={
                'verbose_name': 'Imagem do Sítio',
                'verbose_name_plural': 'Imagens do Sítio',
            },
        ),
        migrations.AddField(
            model_name='funerarysite',
            name='references',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='funeral.Reference'),
        ),
        migrations.AddField(
            model_name='funerarysite',
            name='site_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='funeral.SiteType'),
        ),
    ]
